// generated by stringer -type=ElementType; DO NOT EDIT

package kind

import "fmt"

const _ElementType_name = "BlockInline"

var _ElementType_index = [...]uint8{5, 11}

func (i ElementType) String() string {
	if i < 0 || i >= ElementType(len(_ElementType_index)) {
		return fmt.Sprintf("ElementType(%d)", i)
	}
	hi := _ElementType_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _ElementType_index[i-1]
	}
	return _ElementType_name[lo:hi]
}
